image: docker:latest

services:
  - docker:dind

stages:
  - build
  - deploy

build:
  stage: build
  tags:
    - docker
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA"

deploy beta:
  image: thisiskj/kubectl-envsubst
  stage: deploy
  environment:
    name: beta-$CI_COMMIT_REF_SLUG
    url: https://beta.postal-codes.api.arkangeles.co/$CI_COMMIT_REF_SLUG
    on_stop: stop_beta
  script:
    - kubectl create secret docker-registry gitlab-registry --docker-server=$CI_REGISTRY --docker-username=$CI_DEPLOY_USER --docker-password=$CI_DEPLOY_PASSWORD --save-config --dry-run -o yaml > secret.yaml
    - NODE_ENV=beta CI_DEPLOY_HOST=beta.postal-codes.api.arkangeles.co CI_COMMIT_TAG=$CI_COMMIT_REF_SLUG envsubst < deployment-template.yaml > deployment.yaml
    - kubectl apply -f deployment.yaml -f secret.yaml

deploy production:
  image: thisiskj/kubectl-envsubst
  stage: deploy
  environment:
    name: production-$CI_COMMIT_REF_SLUG
    url: https://postal-codes.api.arkangeles.co/$CI_COMMIT_REF_SLUG
    on_stop: stop_production
  when: manual
  script:
    - NODE_ENV=production CI_DEPLOY_HOST=postal-codes.api.arkangeles.co envsubst < deployment-template.yaml > deployment.yaml
    - kubectl apply -f deployment.yaml

stop_beta:
  image: thisiskj/kubectl-envsubst
  stage: deploy
  script:
    - echo "Remove beta-$CI_COMMIT_REF_SLUG"
    - CI_DEPLOY_HOST=deleted.postal-codes.api.arkangeles.co envsubst < deployment-template.yaml > deployment.yaml
    - kubectl delete -f deployment.yaml
  when: manual
  environment:
    name: beta-$CI_COMMIT_REF_SLUG
    action: stop

stop_production:
  image: thisiskj/kubectl-envsubst
  stage: deploy
  script:
    - echo "Remove production-$CI_COMMIT_REF_SLUG"
    - CI_DEPLOY_HOST=deleted.postal-codes.api.arkangeles.co envsubst < deployment-template.yaml > deployment.yaml
    - kubectl delete -f deployment.yaml
  when: manual
  environment:
    name: production-$CI_COMMIT_REF_SLUG
    action: stop
