version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: development.dockerfile
    command: flask run --host=0.0.0.0
    working_dir: /usr/src/api/
    volumes:
      - ./:/usr/src/api/
    ports:
      - 5000:5000
    environment:
      FLASK_APP: app.main.py
      FLASK_ENV: development
      HOST: 0.0.0.0
      PORT: 5000
      DEBUG: "true"